version: '3.9'
services:
  crm-nginx:
    image: nginx:latest
    container_name: crm-nginx
    working_dir: /app
    depends_on:
      - crm-php-fpm
    volumes:
      - .:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"

  crm-php-fpm:
    container_name: crm-php-fpm
    build:
      context: .docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NGINX_PORT=${NGINX_PORT}

  crm-db:
    container_name: crm-db
    build:
      context: .docker/db
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    volumes:
      - ${DATABASES_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
