version: '3.9'
services:
  crm-nginx:
    image: nginx:latest
    container_name: crm-nginx
    working_dir: /app
    depends_on:
      - crm-php-fpm
    volumes:
      - .:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"

  crm-php-fpm:
    container_name: crm-php-fpm
    build: .docker/php-fpm
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NGINX_PORT=${NGINX_PORT}

  crm-db:
    container_name: crm-db
    image: mysql:8.4
    volumes:
      - ${DATABASES_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - "${MYSQL_PORT}:3306"
